# Generated by Django 3.0.8 on 2020-07-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя героя')),
                ('description', models.TextField(verbose_name='описание героя')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='стоимость героя')),
                ('image', models.ImageField(upload_to='heroes/image', verbose_name='изображение героя')),
                ('photo1', models.ImageField(blank=True, upload_to='heroes/photo', verbose_name='фотография 1')),
                ('photo2', models.ImageField(blank=True, upload_to='heroes/photo', verbose_name='фотография 2')),
                ('photo3', models.ImageField(blank=True, upload_to='heroes/photo', verbose_name='фотография 3')),
                ('photo4', models.ImageField(blank=True, upload_to='heroes/photo', verbose_name='фотография 4')),
                ('photo5', models.ImageField(blank=True, upload_to='heroes/photo', verbose_name='фотография 5')),
            ],
        ),
    ]
