# Generated by Django 3.0.8 on 2020-08-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Герой', 'verbose_name_plural': 'Герои'},
        ),
        migrations.AddField(
            model_name='hero',
            name='slug',
            field=models.SlugField(default=1, verbose_name='ссылка на героя'),
        ),
    ]
