# Generated by Django 3.0.8 on 2020-07-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название квеста')),
                ('image', models.ImageField(upload_to='quests/image', verbose_name='картинка квеста')),
                ('min_description', models.CharField(max_length=170, verbose_name='краткое описание')),
                ('description', models.TextField(verbose_name='описание')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='стоимость квеста')),
                ('photo1', models.ImageField(blank=True, upload_to='quests/photo', verbose_name='фотография 1')),
                ('photo2', models.ImageField(blank=True, upload_to='quests/photo', verbose_name='фотография 2')),
                ('photo3', models.ImageField(blank=True, upload_to='quests/photo', verbose_name='фотография 3')),
                ('photo4', models.ImageField(blank=True, upload_to='quests/photo', verbose_name='фотография 4')),
                ('photo5', models.ImageField(blank=True, upload_to='quests/photo', verbose_name='фотография 5')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
            },
        ),
    ]
