# Generated by Django 3.0.8 on 2020-08-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='part1',
            field=models.CharField(default=1, max_length=50, verbose_name='пункт 1, входящий в квест'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='part2',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 2, входящий в квест'),
        ),
        migrations.AddField(
            model_name='quest',
            name='part3',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 3, входящий в квест'),
        ),
        migrations.AddField(
            model_name='quest',
            name='part4',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 4, входящий в квест'),
        ),
        migrations.AddField(
            model_name='quest',
            name='part5',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 5, входящий в квест'),
        ),
        migrations.AddField(
            model_name='quest',
            name='part6',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 6, входящий в квест'),
        ),
        migrations.AddField(
            model_name='quest',
            name='part7',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 7, входящий в квест'),
        ),
        migrations.AddField(
            model_name='quest',
            name='slug',
            field=models.SlugField(default=1, verbose_name='ссылка на квест'),
        ),
    ]
