# Generated by Django 3.0.8 on 2020-08-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20200804_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='ссылка на квест'),
        ),
    ]
