# Generated by Django 3.0.8 on 2020-07-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='cost',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='стоимость дополнения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addition',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='additions/photo', verbose_name='фотография 1'),
        ),
        migrations.AlterField(
            model_name='addition',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='additions/photo', verbose_name='фотография 2'),
        ),
        migrations.AlterField(
            model_name='addition',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='additions/photo', verbose_name='фотография 3'),
        ),
        migrations.AlterField(
            model_name='addition',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='additions/photo', verbose_name='фотография 4'),
        ),
        migrations.AlterField(
            model_name='addition',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='additions/photo', verbose_name='фотография 5'),
        ),
    ]
