# Generated by Django 3.0.8 on 2020-08-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0003_addition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='ссылка на дополнение'),
        ),
    ]
