# Generated by Django 3.0.8 on 2020-08-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0004_auto_20200803_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='part1',
            field=models.CharField(default=1, max_length=50, verbose_name='пункт 1, входящий в дополнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addition',
            name='part2',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 2, входящий в дополнение'),
        ),
        migrations.AddField(
            model_name='addition',
            name='part3',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 3, входящий в дополнение'),
        ),
        migrations.AddField(
            model_name='addition',
            name='part4',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 4, входящий в дополнение'),
        ),
        migrations.AddField(
            model_name='addition',
            name='part5',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 5, входящий в дополнение'),
        ),
        migrations.AddField(
            model_name='addition',
            name='part6',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 6, входящий в дополнение'),
        ),
        migrations.AddField(
            model_name='addition',
            name='part7',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 7, входящий в дополнение'),
        ),
    ]
