# Generated by Django 3.0.8 on 2020-08-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20200804_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='part1',
            field=models.CharField(max_length=50, verbose_name='пункт 1, входящий в шоу'),
        ),
        migrations.AlterField(
            model_name='show',
            name='part2',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 2, входящий в шоу'),
        ),
        migrations.AlterField(
            model_name='show',
            name='part3',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 3, входящий в шоу'),
        ),
        migrations.AlterField(
            model_name='show',
            name='part4',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 4, входящий в шоу'),
        ),
        migrations.AlterField(
            model_name='show',
            name='part5',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 5, входящий в шоу'),
        ),
        migrations.AlterField(
            model_name='show',
            name='part6',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 6, входящий в шоу'),
        ),
        migrations.AlterField(
            model_name='show',
            name='part7',
            field=models.CharField(blank=True, max_length=50, verbose_name='пункт 7, входящий в шоу'),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(verbose_name='ссылка на шоу'),
        ),
    ]
